openapi: "3.0.3"
info:
  title: go-kakeibo
  version: "0.0.1"
servers:
  - url: http://localhost:8080
paths:
  /v1/categories:
    get:
      tags:
        - "Category"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/V1CategoriesRes"
  /v1/health:
    get:
      tags:
        - "System"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1HealthRes"
  /v1/transactions:
    get:
      tags:
        - "Transaction"
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Sort"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/V1TransactionsRes"
    post:
      tags:
        - "Transaction"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1TransactionsPostReq"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
  /v1/transactions/{transactionId}:
    parameters:
      - $ref: "#/components/parameters/TransactionId"
    get:
      tags:
        - "Transaction"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
    put:
      tags:
        - "Transaction"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1TransactionsTransactionIdPutReq"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
    delete:
      tags:
        - "Transaction"
      responses:
        "200":
          description: ""
components:
  parameters:
    Limit:
      name: limit
      in: query
      schema:
        type: integer
    Sort:
      name: sort
      in: query
      schema:
        type: string
    TransactionId:
      name: transactionId
      in: path
      required: true
      schema:
        type: integer
  schemas:
    V1CategoriesRes:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    V1HealthRes:
      type: object
      properties:
        status:
          type: string
        version:
          type: string
    V1TransactionsPostReq:
      type: object
      required:
        - "date"
        - "type"
        - "categoryId"
        - "amount"
      properties:
        date:
          type: string
          format: date
        type:
          type: integer
          enum:
            - 0
            - 1
          description: >
            Transaction type:
              * 0 - income
              * 1 - expense
        categoryId:
          type: integer
        amount:
          type: integer
          minimum: 1
          maximum: 999999999
        note:
          type: string
          maxLength: 1000
    V1TransactionsTransactionIdPutReq:
      type: object
      required:
        - "date"
        - "type"
        - "categoryId"
        - "amount"
      properties:
        date:
          type: string
          format: date
        type:
          type: integer
          enum:
            - 0
            - 1
          description: >
            Transaction type:
              * 0 - income
              * 1 - expense
        categoryId:
          type: integer
        amount:
          type: integer
          minimum: 1
          maximum: 999999999
        note:
          type: string
          maxLength: 1000
    V1TransactionsRes:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        type:
          type: integer
          enum:
            - 0
            - 1
          description: >
            Transaction type:
              * 0 - income
              * 1 - expense
        categoryId:
          type: integer
        amount:
          type: integer
        note:
          type: string
