openapi: "3.0.3"
info:
  title: go-kakeibo
  version: "0.0.1"
servers:
  - url: http://localhost:8080
paths:
  /v1/categories:
    get:
      tags:
        - "Category"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: "#/components/schemas/Metadata"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/V1CategoriesRes"
  /v1/health:
    get:
      tags:
        - "System"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1HealthRes"
  /v1/transactions:
    get:
      tags:
        - "Transaction"
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Sort"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: "#/components/schemas/Metadata"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/V1TransactionsRes"
    post:
      tags:
        - "Transaction"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1TransactionsPostReq"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
  /v1/transactions/{transaction_id}:
    parameters:
      - $ref: "#/components/parameters/TransactionId"
    get:
      tags:
        - "Transaction"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
    patch:
      tags:
        - "Transaction"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1TransactionsTransactionIdPatchReq"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/V1TransactionsRes"
    delete:
      tags:
        - "Transaction"
      responses:
        "200":
          description: ""
components:
  parameters:
    Limit:
      name: limit
      in: query
      schema:
        type: integer
    Sort:
      name: sort
      in: query
      schema:
        type: string
    TransactionId:
      name: transaction_id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    Metadata:
      type: object
      properties:
        current_page:
          type: integer
          x-go-omitempty: true
        page_size:
          type: integer
          x-go-omitempty: true
        first_page:
          type: integer
          x-go-omitempty: true
        last_page:
          type: integer
          x-go-omitempty: true
        total_records:
          type: integer
          x-go-omitempty: true
    V1CategoriesRes:
      type: object
      properties:
        id:
          type: integer
        type:
          type: integer
          description: >
            Transaction type:
              * 1 - income
              * 2 - expense
        type_name:
          type: string
        name:
          type: string
    V1HealthRes:
      type: object
      properties:
        status:
          type: string
        version:
          type: string
    V1TransactionsPostReq:
      type: object
      required:
        - "date"
        - "category_id"
        - "amount"
      properties:
        date:
          type: string
          format: date
          x-go-validate: required,datetime=2006-01-02
        category_id:
          type: integer
          x-go-validate: min=1,max=999999999
        amount:
          type: integer
          minimum: 1
          maximum: 999999999
          x-go-validate: min=1,max=999999999
        note:
          type: string
          maxLength: 1000
          x-go-validate: max=1000
    V1TransactionsTransactionIdPatchReq:
      type: object
      properties:
        date:
          type: string
          nullable: true
          format: date
          x-go-validate: omitempty,datetime=2006-01-02
        category_id:
          type: integer
          nullable: true
          x-go-validate: omitempty,min=1,max=999999999
        amount:
          type: integer
          nullable: true
          minimum: 1
          maximum: 999999999
          x-go-validate: omitempty,min=1,max=999999999
        note:
          type: string
          nullable: true
          maxLength: 1000
          x-go-validate: omitempty,max=1000
    V1TransactionsRes:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        type:
          type: integer
          description: >
            Transaction type:
              * 1 - income
              * 2 - expense
        type_name:
          type: string
        category_id:
          type: integer
        category_name:
          type: string
        amount:
          type: integer
        note:
          type: string
