// Code generated by xo. DO NOT EDIT.

package entity

import (
	"time"
)

// Generated from 'kakeibo.categories'.
type Category struct {
	ID         int       // id
	Type       int       // type
	Name       string    // name
	CreatedAt  time.Time // created_at
	ModifiedAt time.Time // modified_at
}
