// Code generated by xo. DO NOT EDIT.

package entity

import (
	"time"
)

// Generated from 'kakeibo.incomes'.
type Income struct {
	ID         int       // id
	UserID     int       // user_id
	Date       time.Time // date
	CategoryID int       // category_id
	Amount     int       // amount
	Comment    string    // comment
	CreatedAt  time.Time // created_at
	ModifiedAt time.Time // modified_at
}
