// Code generated by xo. DO NOT EDIT.

package entity

import (
	"time"
)

// Generated from 'kakeibo.transactions'.
type Transaction struct {
	ID         int       // id
	UserID     int       // user_id
	Date       time.Time // date
	CategoryID int       // category_id
	Amount     int       // amount
	Note       string    // note
	CreatedAt  time.Time // created_at
	ModifiedAt time.Time // modified_at
	Version    int       // version
}
