// Code generated by xo. DO NOT EDIT.

package entity

import (
	"time"
)

// Generated from 'kakeibo.users'.
type User struct {
	ID            int       // id
	LoginID       string    // login_id
	LoginPassword string    // login_password
	CreatedAt     time.Time // created_at
	ModifiedAt    time.Time // modified_at
	Version       int       // version
}
