// Code generated by xo. DO NOT EDIT.

package repository

import (
	"github.com/yjmurakami/go-kakeibo/internal/database"
	"github.com/yjmurakami/go-kakeibo/internal/entity"
)

// Generated from 'kakeibo.expenses'.
type expenseRepository struct{}

func NewExpenseRepository() *expenseRepository {
	return &expenseRepository{}
}

func (r *expenseRepository) SelectAll(db database.DB) ([]*entity.Expense, error) {
	query := `
		SELECT id, user_id, date, category_id, amount, comment, created_at, modified_at
		FROM kakeibo.expenses
		ORDER BY id
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	s := []*entity.Expense{}
	for rows.Next() {
		e := entity.Expense{}
		err = rows.Scan(&e.ID, &e.UserID, &e.Date, &e.CategoryID, &e.Amount, &e.Comment, &e.CreatedAt, &e.ModifiedAt)
		if err != nil {
			return nil, err
		}
		s = append(s, &e)
	}

	err = rows.Err()
	if err != nil {
		return nil, err
	}
	return s, nil
}

func (r *expenseRepository) Insert(db database.DB, e *entity.Expense) error {
	query := `
		INSERT INTO kakeibo.expenses (
			user_id, date, category_id, amount, comment, created_at, modified_at
		) VALUES (
			?, ?, ?, ?, ?, ?, ?
		)
	`

	res, err := db.Exec(query, e.UserID, e.Date, e.CategoryID, e.Amount, e.Comment, e.CreatedAt, e.ModifiedAt)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	e.ID = int(id)
	return nil
}

func (r *expenseRepository) Update(db database.DB, e *entity.Expense) error {
	query := `
		UPDATE kakeibo.expenses SET
			user_id = ?, date = ?, category_id = ?, amount = ?, comment = ?, created_at = ?, modified_at = ?
		WHERE id = ?
	`

	_, err := db.Exec(query, e.UserID, e.Date, e.CategoryID, e.Amount, e.Comment, e.CreatedAt, e.ModifiedAt, e.ID)
	return err
}

func (r *expenseRepository) Delete(db database.DB, e *entity.Expense) error {
	query := `
		DELETE FROM kakeibo.expenses
		WHERE id = ?
	`

	_, err := db.Exec(query, e.ID)
	return err
}

// Generated from index 'category_id'.
func (r *expenseRepository) SelectByCategoryID(db database.DB, categoryID int) ([]*entity.Expense, error) {
	query := `
		SELECT id, user_id, date, category_id, amount, comment, created_at, modified_at
		FROM kakeibo.expenses
		WHERE category_id = ?
		ORDER BY id
	`
	rows, err := db.Query(query, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	s := []*entity.Expense{}
	for rows.Next() {
		e := entity.Expense{}
		err = rows.Scan(&e.ID, &e.UserID, &e.Date, &e.CategoryID, &e.Amount, &e.Comment, &e.CreatedAt, &e.ModifiedAt)
		if err != nil {
			return nil, err
		}
		s = append(s, &e)
	}

	err = rows.Err()
	if err != nil {
		return nil, err
	}
	return s, nil
}

// Generated from index 'expenses_id_pkey'.
func (r *expenseRepository) SelectByID(db database.DB, id int) (*entity.Expense, error) {
	query := `
		SELECT id, user_id, date, category_id, amount, comment, created_at, modified_at
		FROM kakeibo.expenses
		WHERE id = ?
	`
	e := entity.Expense{}
	err := db.QueryRow(query, id).Scan(&e.ID, &e.UserID, &e.Date, &e.CategoryID, &e.Amount, &e.Comment, &e.CreatedAt, &e.ModifiedAt)
	if err != nil {
		return nil, err
	}
	return &e, nil
}

// Generated from index 'user_id'.
func (r *expenseRepository) SelectByUserID(db database.DB, userID int) ([]*entity.Expense, error) {
	query := `
		SELECT id, user_id, date, category_id, amount, comment, created_at, modified_at
		FROM kakeibo.expenses
		WHERE user_id = ?
		ORDER BY id
	`
	rows, err := db.Query(query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	s := []*entity.Expense{}
	for rows.Next() {
		e := entity.Expense{}
		err = rows.Scan(&e.ID, &e.UserID, &e.Date, &e.CategoryID, &e.Amount, &e.Comment, &e.CreatedAt, &e.ModifiedAt)
		if err != nil {
			return nil, err
		}
		s = append(s, &e)
	}

	err = rows.Err()
	if err != nil {
		return nil, err
	}
	return s, nil
}
