api:
  port: 8080
  idleTimeout: 60s
  readTimeout: 10s
  writeTimeout: 30s
  jwtKey: secret
  jwtExpiration: 5m

mysql:
  host: mysql-server
  port: 3306
  username: root
  password: password
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: 15m

mysqlTest:
  host: mysql-server-test
  port: 3306
  username: root
  password: password
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: 15m
