// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package server

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/yjmurakami/go-kakeibo/cmd/api/handler"
)

func newRouter(m handler.MiddlewareHandler, hc handlerConfig) http.Handler {
	CategoryHandler := initCategoryHandler(hc)
	IncomeHandler := initIncomeHandler(hc)
	SystemHandler := initSystemHandler(hc)

	mux := mux.NewRouter()

	mux.HandleFunc("/api/v1/categories", m.HandleError(CategoryHandler.V1CategoriesGet())).Methods("GET")

	mux.HandleFunc("/api/v1/incomes", m.HandleError(IncomeHandler.V1IncomesGet())).Methods("GET")
	mux.HandleFunc("/api/v1/incomes/{incomeId}", m.HandleError(IncomeHandler.V1IncomesIncomeIdDelete())).Methods("DELETE")
	mux.HandleFunc("/api/v1/incomes/{incomeId}", m.HandleError(IncomeHandler.V1IncomesIncomeIdGet())).Methods("GET")
	mux.HandleFunc("/api/v1/incomes/{incomeId}", m.HandleError(IncomeHandler.V1IncomesIncomeIdPut())).Methods("PUT")
	mux.HandleFunc("/api/v1/incomes", m.HandleError(IncomeHandler.V1IncomesPost())).Methods("POST")

	mux.HandleFunc("/api/v1/health", m.HandleError(SystemHandler.V1HealthGet())).Methods("GET")

	return mux
}
