// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package server

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/yjmurakami/go-kakeibo/cmd/api/handler"
)

func newRouter(m handler.MiddlewareHandler, hc handlerConfig) http.Handler {
	CategoryHandler := initCategoryHandler(hc)
	SystemHandler := initSystemHandler(hc)
	TransactionHandler := initTransactionHandler(hc)

	mux := mux.NewRouter()
	mux.NotFoundHandler = http.HandlerFunc(handler.NotFoundError)
	mux.MethodNotAllowedHandler = http.HandlerFunc(handler.MethodNotAllowedError)

	mux.HandleFunc("/api/v1/categories", CategoryHandler.V1CategoriesGet()).Methods("GET")

	mux.HandleFunc("/api/v1/health", SystemHandler.V1HealthGet()).Methods("GET")

	mux.HandleFunc("/api/v1/transactions", TransactionHandler.V1TransactionsGet()).Methods("GET")
	mux.HandleFunc("/api/v1/transactions", TransactionHandler.V1TransactionsPost()).Methods("POST")
	mux.HandleFunc("/api/v1/transactions/{transactionId}", TransactionHandler.V1TransactionsTransactionIdDelete()).Methods("DELETE")
	mux.HandleFunc("/api/v1/transactions/{transactionId}", TransactionHandler.V1TransactionsTransactionIdGet()).Methods("GET")
	mux.HandleFunc("/api/v1/transactions/{transactionId}", TransactionHandler.V1TransactionsTransactionIdPut()).Methods("PUT")

	return mux
}
