// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package openapi

type V1IncomesPostReq struct {
	Date       string `json:"date"`
	CategoryId int    `json:"categoryId"`
	Amount     int    `json:"amount"`
	Note       string `json:"note"`
}
