// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package openapi

type V1TransactionsRes struct {
	Id         int    `json:"id"`
	Date       string `json:"date"`
	Type       int    `json:"type"` // Transaction type:   * 0 - income   * 1 - expense
	CategoryId int    `json:"categoryId"`
	Amount     int    `json:"amount"`
	Note       string `json:"note"`
}
