// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package handler

import "net/http"

type CategoryHandler interface { 
	V1CategoriesGet() func(w http.ResponseWriter, r *http.Request) error
}

type SystemHandler interface { 
	V1HealthGet() func(w http.ResponseWriter, r *http.Request) error
}

type TransactionHandler interface { 
	V1TransactionsGet() func(w http.ResponseWriter, r *http.Request) error
	V1TransactionsPost() func(w http.ResponseWriter, r *http.Request) error
	V1TransactionsTransactionIdDelete() func(w http.ResponseWriter, r *http.Request) error
	V1TransactionsTransactionIdGet() func(w http.ResponseWriter, r *http.Request) error
	V1TransactionsTransactionIdPut() func(w http.ResponseWriter, r *http.Request) error
}
