// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package handler

import "net/http"

type CategoryHandler interface {
	V1CategoriesGet() func(w http.ResponseWriter, r *http.Request) error
}

type IncomeHandler interface {
	V1IncomesGet() func(w http.ResponseWriter, r *http.Request) error
	V1IncomesIncomeIdDelete() func(w http.ResponseWriter, r *http.Request) error
	V1IncomesIncomeIdGet() func(w http.ResponseWriter, r *http.Request) error
	V1IncomesIncomeIdPut() func(w http.ResponseWriter, r *http.Request) error
	V1IncomesPost() func(w http.ResponseWriter, r *http.Request) error
}

type SystemHandler interface {
	V1HealthGet() func(w http.ResponseWriter, r *http.Request) error
}
