// Code generated by openapi-generator; DO NOT EDIT.
// API version: 0.0.1

package handler

import "net/http"

type CategoryHandler interface { 
	V1CategoriesGet() http.HandlerFunc
}

type SystemHandler interface { 
	V1HealthGet() http.HandlerFunc
}

type TransactionHandler interface { 
	V1TransactionsGet() http.HandlerFunc
	V1TransactionsPost() http.HandlerFunc
	V1TransactionsTransactionIdDelete() http.HandlerFunc
	V1TransactionsTransactionIdGet() http.HandlerFunc
	V1TransactionsTransactionIdPatch() http.HandlerFunc
}
